name: Linux Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            pkg-config \
            libgl1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxinerama-dev \
            libxcursor-dev \
            libsodium-dev

      - name: Cache raylib
        id: cache-raylib
        uses: actions/cache@v3
        with:
          path: raylib-build
          key: ${{ runner.os }}-raylib-5.0

      - name: Build raylib
        if: steps.cache-raylib.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch '5.0' https://github.com/raysan5/raylib.git
          cd raylib
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=OFF ..
          make
          sudo make install
          cd ../..
          mkdir -p raylib-build
          cp -r raylib/build/* raylib-build/

      - name: Install cached raylib
        if: steps.cache-raylib.outputs.cache-hit == 'true'
        run: |
          cd raylib-build
          sudo make install
          cd ..

      - name: Build Project
        run: |
          make
          mkdir -p artifacts/habits-linux-x86_64
          cp build/habits artifacts/habits-linux-x86_64/
          
          # Create assets directory and copy images and fonts
          mkdir -p artifacts/habits-linux-x86_64/assets
          mkdir -p artifacts/habits-linux-x86_64/assets/images
          mkdir -p artifacts/habits-linux-x86_64/assets/fonts
          cp -r images/* artifacts/habits-linux-x86_64/assets/images/
          cp -r fonts/* artifacts/habits-linux-x86_64/assets/fonts/
          
          cd artifacts
          tar czf habits-linux-x86_64.tar.gz habits-linux-x86_64/

      - name: Create AppImage
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          
          # Install FUSE
          sudo apt-get update
          sudo apt-get install -y libfuse2
          
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          mkdir -p AppDir/usr/share/habits/assets/images
          mkdir -p AppDir/usr/share/habits/assets/fonts
          
          # Copy executable
          cp build/habits AppDir/usr/bin/
          
          # Copy assets
          cp -r images/* AppDir/usr/share/habits/assets/images/
          cp -r fonts/* AppDir/usr/share/habits/assets/fonts/
          
          # Create AppRun file
          cat > AppDir/AppRun << 'EOF'
#!/bin/bash
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin/:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${LD_LIBRARY_PATH}"
cd "${HERE}/usr/share/habits"
exec "${HERE}/usr/bin/habits" "$@"
EOF
          chmod +x AppDir/AppRun
          
          # Copy desktop file
          cp packaging/linux/habits.desktop AppDir/
          cp packaging/linux/habits.desktop AppDir/usr/share/applications/
          
          # Copy icon files - important: copy directly to root with exact name from desktop file
          cp packaging/linux/habits.png AppDir/habits.png
          cp packaging/linux/habits.png AppDir/usr/share/icons/hicolor/256x256/apps/
          
          # Use the extract option to avoid FUSE issues
          ./appimagetool --appimage-extract
          ARCH=x86_64 ./squashfs-root/AppRun AppDir artifacts/Habits-x86_64.AppImage
   
      - name: Generate date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ steps.date.outputs.date }}
          name: Build ${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
          files: |
            artifacts/habits-linux-x86_64.tar.gz
            artifacts/Habits-x86_64.AppImage