name: Linux Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Install Dependencies
        run: |
          sudo add-apt-repository ppa:appimagelauncher-team/stable
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            appimagetool \
            pkg-config \
            libgl1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxinerama-dev \
            libxcursor-dev \
            libsodium-dev

      - name: Cache raylib
        id: cache-raylib
        uses: actions/cache@v3
        with:
          path: raylib-build
          key: ${{ runner.os }}-raylib-5.0

      - name: Build raylib
        if: steps.cache-raylib.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch '5.0' https://github.com/raysan5/raylib.git
          cd raylib
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=OFF ..
          make
          sudo make install
          cd ../..
          mkdir -p raylib-build
          cp -r raylib/build/* raylib-build/

      - name: Install cached raylib
        if: steps.cache-raylib.outputs.cache-hit == 'true'
        run: |
          cd raylib-build
          sudo make install
          cd ..

      - name: Build Project
        run: |
          make
          mkdir -p artifacts/habits-linux-x86_64
          cp build/habits artifacts/habits-linux-x86_64/
          cp -r build/assets artifacts/habits-linux-x86_64/
          cd artifacts
          tar czf habits-linux-x86_64.tar.gz habits-linux-x86_64/

      - name: Create AppImage
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          
          cp build/habits AppDir/usr/bin/
          cp -r build/assets AppDir/usr/share/
          cp packaging/linux/habits.desktop AppDir/usr/share/applications/
          cp packaging/linux/habits.png AppDir/usr/share/icons/hicolor/256x256/apps/
          
          ./appimagetool AppDir artifacts/Habits-x86_64.AppImage

      - name: Generate date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ steps.date.outputs.date }}
          name: Build ${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
          files: |
            artifacts/habits-linux-x86_64.tar.gz
            artifacts/Habits-x86_64.AppImage
            
